from __future__ import annotations
import sys
from pathlib import Path

# Need to properly point to MinerU dir
CURRENT_DIR = Path(__file__).resolve().parent
MINERU_DIR = CURRENT_DIR.parent / "data_preprocess" / "MinerU"

if str(MINERU_DIR) not in sys.path:
    sys.path.insert(0, str(MINERU_DIR))

# Add project root to sys.path for utils imports
PROJECT_ROOT = CURRENT_DIR.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import base64
from mineru.cli.common import do_parse, read_fn
from utils.llm_clients.local_llm import LocalLLMClient


def _parse_subdir(backend: str, method: str) -> str:
    if backend == "pipeline":
        return method
    if backend.startswith("hybrid-"):
        return f"hybrid_{method}"
    if backend.startswith("vlm-"):
        return "vlm"
    return method


def extract_pdf_mineru(
    input_path: str | Path,
    output_dir: str | Path,
    backend: str = "hybrid-auto-engine",
    method: str = "auto",
    lang: str = "en",
    url: str | None = None,
    start: int = 0,
    end: int | None = None,
) -> Path:
    """
    Extract data from a PDF file using MinerU.
    
    Args:
        input_path: Path to the input PDF file.
        output_dir: Directory where the output will be saved.
        backend: MinerU backend to use.
        method: MinerU parse method.
        lang: Language of the PDF.
        url: Server URL for MinerU, if applicable.
        start: Start page id.
        end: End page id.
        
    Returns:
        Path: Path to the extracted markdown file.
    """
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    do_parse(
        output_dir=str(output_dir),
        pdf_file_names=[input_path.stem],
        pdf_bytes_list=[read_fn(input_path)],
        p_lang_list=[lang],
        backend=backend,
        parse_method=method,
        server_url=url,
        start_page_id=start,
        end_page_id=end,
    )
    
    expected_md = output_dir / input_path.stem / _parse_subdir(backend, method) / f"{input_path.stem}.md"
    if not expected_md.exists():
        raise RuntimeError(f"MinerU did not produce expected output: {expected_md}")
        
    return expected_md


def describe_mineru_images(json_path: str | Path):
    """
    Reads the object list JSON generated by MinerU, describes any images 
    found using a local LLM, and adds a 'description' key to those items 
    to be used as an index for RAG.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        raise FileNotFoundError(f"JSON file not found: {json_path}")
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    print("Initializing client...")
    client = LocalLLMClient(
        model_name="qwen2.5-vl-72b-instruct",
        base_url="http://localhost:8000/v1",
        api_key="local-dev-key",
    )
    
    modified = False
    for idx, item in enumerate(data):
        if item.get("type") == "image":
            # Skip if already described
            if "description" in item and item["description"]:
                print(f"Skipping {item.get('img_path', 'unknown')}, already described.")
                continue

            img_rel_path = item.get("img_path")
            if not img_rel_path:
                print("Warning: Image type item has no img_path.")
                continue
                
            # The image path is relative to the directory containing the JSON file
            img_full_path = json_path.parent / img_rel_path
            
            if not img_full_path.exists():
                print(f"Image not found: {img_full_path}")
                continue

            # Gather surrounding text context
            context_text = ""
            if idx > 0 and data[idx - 1].get("type") == "text":
                context_text += f"Previous text:\n{data[idx - 1].get('text', '')}\n\n"
            if idx < len(data) - 1 and data[idx + 1].get("type") == "text":
                context_text += f"Next text:\n{data[idx + 1].get('text', '')}\n\n"
                
            try:
                with open(img_full_path, "rb") as img_file:
                    base64_img = base64.b64encode(img_file.read()).decode("utf-8")
                    
                context_instruction = f"Context:\n{context_text}\n\n" if context_text else ""

                user_prompt_text = (
                    f"{context_instruction}"
                    "Task: Generate a search index summary for this image. Keep it short and simple. Provide:\n"
                    "1. Type & Subject: (e.g., Scatter plot showing GDP vs. Inflation)\n"
                    "2. Labels & Legends: (List exact axis labels and legend keys)\n"
                    "3. Key Findings: (Extract the main trend, anomaly, or relationship shown)\n"
                    "4. Keywords: (Comma-separated list of core economic terms and entities)"
                )

                # Provide the image using the OpenAI-compatible multimodal format
                user_prompt = [
                    {
                        "type": "text",
                        "text": user_prompt_text
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_img}"
                        }
                    }
                ]
                
                print(f"Describing image: {img_rel_path}")
                response = client.generate_response(
                    user_prompt=user_prompt, # type: ignore
                    system_prompt="You are an expert data extraction system. Your output is used directly for dense vector retrieval of economics and academic papers. Prioritize entities, exact axis labels, data trends, and terminology. Be concise and highly structured. Do not use conversational filler.",
                    response_mime_type="text/plain",
                    max_tokens=2048
                )
                print(response)
                item["description"] = response
                modified = True
                print(f"Description added for {img_rel_path}")
                
                # Incrementally save progress to avoid data loss if interrupted
                with open(json_path, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=4, separators=(',', ': '), ensure_ascii=False)
                    
            except Exception as e:
                print(f"Error describing {img_rel_path}: {e}")
                
    if modified:
        print(f"Finished updating {json_path} with descriptions.")
    else:
        print("No new images were described.")


def describe_mineru_equations(json_path: str | Path):
    """
    Reads the object list JSON generated by MinerU, describes any equations 
    found using a local LLM, and adds a 'description' key to those items 
    to be used as an index for RAG.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        raise FileNotFoundError(f"JSON file not found: {json_path}")
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    print("Initializing client...")
    client = LocalLLMClient(
        model_name="qwen2.5-vl-72b-instruct",
        base_url="http://localhost:8000/v1",
        api_key="local-dev-key",
    )
    
    modified = False
    for idx, item in enumerate(data):
        if item.get("type") == "equation":
            # Skip if already described
            if "description" in item and item["description"]:
                print(f"Skipping equation {item.get('img_path', 'unknown')}, already described.")
                continue

            img_rel_path = item.get("img_path")
            equation_text = item.get("text", "")
            
            if not img_rel_path:
                print("Warning: Equation type item has no img_path.")
                continue
                
            # The image path is relative to the directory containing the JSON file
            img_full_path = json_path.parent / img_rel_path
            
            if not img_full_path.exists():
                print(f"Image not found: {img_full_path}")
                continue
                
            # Gather surrounding text context
            context_text = ""
            if idx > 0 and data[idx - 1].get("type") == "text":
                context_text += f"Previous text:\n{data[idx - 1].get('text', '')}\n\n"
            if idx < len(data) - 1 and data[idx + 1].get("type") == "text":
                context_text += f"Next text:\n{data[idx + 1].get('text', '')}\n\n"

            try:
                with open(img_full_path, "rb") as img_file:
                    base64_img = base64.b64encode(img_file.read()).decode("utf-8")
                    
                context_instruction = f"Context:\n{context_text}\n\n" if context_text else ""

                user_prompt_text = (
                    f"{context_instruction}"
                    f"LaTeX: {equation_text}\n\n"
                    "Task: Generate a search index summary for this equation. Keep it short and simple. Provide:\n"
                    "1. Concept: (Name of the theorem, model, or economic principle)\n"
                    "2. Intuition: (What does this equation fundamentally calculate or represent?)\n"
                    "3. Variables: (Define the key variables based on the context)\n"
                    "4. Keywords: (Comma-separated list of core terms)"
                )

                # Provide the image using the OpenAI-compatible multimodal format
                user_prompt = [
                    {
                        "type": "text",
                        "text": user_prompt_text
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_img}"
                        }
                    }
                ]
                
                print(f"Describing equation: {img_rel_path}")
                response = client.generate_response(
                    user_prompt=user_prompt, # type: ignore
                    system_prompt="You are an expert mathematical extraction system. Your output is used directly for dense vector retrieval of economics papers. Focus on defining variables, stating the core mathematical relationship, and extracting the economic intuition. Do not use conversational filler.",
                    response_mime_type="text/plain",
                    max_tokens=2048
                )
                print(response)
                item["description"] = response
                modified = True
                print(f"Description added for {img_rel_path}")
                
                # Incrementally save progress to avoid data loss if interrupted
                with open(json_path, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=4, separators=(',', ': '), ensure_ascii=False)
                    
            except Exception as e:
                print(f"Error describing equation {img_rel_path}: {e}")
                
    if modified:
        print(f"Finished updating {json_path} with equation descriptions.")
    else:
        print("No new equations were described.")


def describe_mineru_tables(json_path: str | Path):
    """
    Reads the object list JSON generated by MinerU, describes any tables 
    found using a local LLM, and adds a 'description' key to those items 
    to be used as an index for RAG.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        raise FileNotFoundError(f"JSON file not found: {json_path}")
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    print("Initializing client...")
    client = LocalLLMClient(
        model_name="qwen2.5-vl-72b-instruct",
        base_url="http://localhost:8000/v1",
        api_key="local-dev-key",
    )
    
    modified = False
    for idx, item in enumerate(data):
        if item.get("type") == "table":
            # Skip if already described
            if "description" in item and item["description"]:
                print(f"Skipping table {item.get('img_path', 'unknown')}, already described.")
                continue

            img_rel_path = item.get("img_path")
            table_caption = "\n".join(item.get("table_caption", [])) if "table_caption" in item else ""
            table_footnote = "\n".join(item.get("table_footnote", [])) if "table_footnote" in item else ""
            table_body = item.get("table_body", "")
            
            if not img_rel_path:
                print("Warning: Table type item has no img_path.")
                continue
                
            # The image path is relative to the directory containing the JSON file
            img_full_path = json_path.parent / img_rel_path
            
            if not img_full_path.exists():
                print(f"Image not found: {img_full_path}")
                continue
                
            # Gather surrounding text context
            context_text = ""
            if idx > 0 and data[idx - 1].get("type") == "text":
                context_text += f"Previous text:\n{data[idx - 1].get('text', '')}\n\n"
            if idx < len(data) - 1 and data[idx + 1].get("type") == "text":
                context_text += f"Next text:\n{data[idx + 1].get('text', '')}\n\n"

            try:
                with open(img_full_path, "rb") as img_file:
                    base64_img = base64.b64encode(img_file.read()).decode("utf-8")
                    
                context_instruction = f"Context:\n{context_text}\n\n" if context_text else ""
                table_info = ""
                if table_caption:
                    table_info += f"Table Caption: {table_caption}\n"
                if table_footnote:
                    table_info += f"Table Footnote: {table_footnote}\n"
                if table_body:
                    table_info += f"Table HTML/Body: {table_body}\n"

                user_prompt_text = (
                    f"{context_instruction}"
                    f"{table_info}\n"
                    "Task: Generate a search index summary for this table. Keep it short and simple. Provide:\n"
                    "1. Subject: (What is this table about? E.g., Cross-Sectional Distributions of Income)\n"
                    "2. Data Metrics: (What variables or metrics are being reported?)\n"
                    "3. Key Findings: (Extract the main trend, anomaly, or insight shown)\n"
                    "4. Keywords: (Comma-separated list of core economic terms and entities)"
                )

                # Provide the image using the OpenAI-compatible multimodal format
                user_prompt = [
                    {
                        "type": "text",
                        "text": user_prompt_text
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_img}"
                        }
                    }
                ]
                
                print(f"Describing table: {img_rel_path}")
                response = client.generate_response(
                    user_prompt=user_prompt, # type: ignore
                    system_prompt="You are an expert data extraction system. Your output is used directly for dense vector retrieval of economics papers. Focus on defining metrics, stating the core data relationships, and extracting the economic intuition. Do not use conversational filler.",
                    response_mime_type="text/plain",
                    max_tokens=2048
                )
                print(response)
                item["description"] = response
                modified = True
                print(f"Description added for {img_rel_path}")
                
                # Incrementally save progress to avoid data loss if interrupted
                with open(json_path, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=4, separators=(',', ': '), ensure_ascii=False)
                    
            except Exception as e:
                print(f"Error describing table {img_rel_path}: {e}")
                
    if modified:
        print(f"Finished updating {json_path} with table descriptions.")
    else:
        print("No new tables were described.")


def main():
    json_file_path = "/home3/davidlcs/Econ-Rag/NTU-DAVID-RAG/tests/output_pdf_extract/Manuscript/auto/Manuscript_content_list.json"
    describe_mineru_images(json_file_path)
    describe_mineru_equations(json_file_path)
    describe_mineru_tables(json_file_path)


if __name__ == "__main__":
    main()
