from __future__ import annotations
import sys
from pathlib import Path

# Need to properly point to MinerU dir
CURRENT_DIR = Path(__file__).resolve().parent
MINERU_DIR = CURRENT_DIR.parent / "data_preprocess" / "MinerU"

if str(MINERU_DIR) not in sys.path:
    sys.path.insert(0, str(MINERU_DIR))

# Add project root to sys.path for utils imports
PROJECT_ROOT = CURRENT_DIR.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import base64
from mineru.cli.common import do_parse, read_fn
from utils.llm_clients.local_llm import LocalLLMClient


def _parse_subdir(backend: str, method: str) -> str:
    if backend == "pipeline":
        return method
    if backend.startswith("hybrid-"):
        return f"hybrid_{method}"
    if backend.startswith("vlm-"):
        return "vlm"
    return method


def extract_pdf_mineru(
    input_path: str | Path,
    output_dir: str | Path,
    backend: str = "hybrid-auto-engine",
    method: str = "auto",
    lang: str = "en",
    url: str | None = None,
    start: int = 0,
    end: int | None = None,
) -> Path:
    """
    Extract data from a PDF file using MinerU.
    
    Args:
        input_path: Path to the input PDF file.
        output_dir: Directory where the output will be saved.
        backend: MinerU backend to use.
        method: MinerU parse method.
        lang: Language of the PDF.
        url: Server URL for MinerU, if applicable.
        start: Start page id.
        end: End page id.
        
    Returns:
        Path: Path to the extracted markdown file.
    """
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    do_parse(
        output_dir=str(output_dir),
        pdf_file_names=[input_path.stem],
        pdf_bytes_list=[read_fn(input_path)],
        p_lang_list=[lang],
        backend=backend,
        parse_method=method,
        server_url=url,
        start_page_id=start,
        end_page_id=end,
    )
    
    expected_md = output_dir / input_path.stem / _parse_subdir(backend, method) / f"{input_path.stem}.md"
    if not expected_md.exists():
        raise RuntimeError(f"MinerU did not produce expected output: {expected_md}")
        
    return expected_md


def describe_mineru_images(json_path: str | Path):
    """
    Reads the object list JSON generated by MinerU, describes any images 
    found using a local LLM, and adds a 'description' key to those items 
    to be used as an index for RAG.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        raise FileNotFoundError(f"JSON file not found: {json_path}")
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    print("Initializing client...")
    client = LocalLLMClient(
        model_name="qwen2.5-vl-72b-instruct",
        base_url="http://localhost:8000/v1",
        api_key="local-dev-key",
    )
    
    modified = False
    for item in data:
        if item.get("type") == "image":
            # Skip if already described
            if "description" in item and item["description"]:
                print(f"Skipping {item.get('img_path', 'unknown')}, already described.")
                continue

            img_rel_path = item.get("img_path")
            if not img_rel_path:
                print("Warning: Image type item has no img_path.")
                continue
                
            # The image path is relative to the directory containing the JSON file
            img_full_path = json_path.parent / img_rel_path
            
            if not img_full_path.exists():
                print(f"Image not found: {img_full_path}")
                continue
                
            try:
                with open(img_full_path, "rb") as img_file:
                    base64_img = base64.b64encode(img_file.read()).decode("utf-8")
                    
                # Provide the image using the OpenAI-compatible multimodal format
                user_prompt = [
                    {
                        "type": "text",
                        "text": "Please provide a detailed and precise description of this image. If it contains charts, graphs, or tables, explicitly extract and describe the key data points, trends, and structural relationships. If it contains text or mathematical formulas, transcribe them accurately. This description will be used directly to index the image for a Retrieval-Augmented Generation (RAG) system, so include all relevant keywords, labels, and contextual information."
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_img}"
                        }
                    }
                ]
                
                print(f"Describing image: {img_rel_path}")
                response = client.generate_response(
                    user_prompt=user_prompt, # type: ignore
                    system_prompt="You are an expert AI assistant specializing in carefully describing academic and economic figures, charts, and equations for RAG indexing.",
                    response_mime_type="text/plain",
                    max_tokens=2048
                )
                print(response)
                item["description"] = response
                modified = True
                print(f"Description added for {img_rel_path}")
                
                # Incrementally save progress to avoid data loss if interrupted
                with open(json_path, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=4, separators=(',', ': '), ensure_ascii=False)
                    
            except Exception as e:
                print(f"Error describing {img_rel_path}: {e}")
                
    if modified:
        print(f"Finished updating {json_path} with descriptions.")
    else:
        print("No new images were described.")


def main():
    json_file_path = "/home3/davidlcs/Econ-Rag/NTU-DAVID-RAG/tests/output_pdf_extract/Manuscript/auto/Manuscript_content_list.json"
    describe_mineru_images(json_file_path)


if __name__ == "__main__":
    main()
